// <auto-generated />
namespace HotelAdvice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_date_to_tblRating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_date_to_tblRating));
        
        string IMigrationMetadata.Id
        {
            get { return "201611010530353_add_date_to_tblRating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
