// <auto-generated />
namespace HotelAdvice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_TBL_Hotel_AND_TBL_CITY : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TBL_Hotel_AND_TBL_CITY));
        
        string IMigrationMetadata.Id
        {
            get { return "201608180551268_add_TBL_Hotel_AND_TBL_CITY"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
