// <auto-generated />
namespace HotelAdvice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_TBL_Room_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TBL_Room_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "201609140513309_add_TBL_Room_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
