// <auto-generated />
namespace HotelAdvice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_relation_hotel_wihList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_relation_hotel_wihList));
        
        string IMigrationMetadata.Id
        {
            get { return "201610211945510_add_relation_hotel_wihList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
