// <auto-generated />
namespace HotelAdvice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterCityTable_addAttractionColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterCityTable_addAttractionColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201608260546489_alterCityTable_addAttractionColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
