// <auto-generated />
namespace HotelAdvice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_tblhotel_distnace_to_float : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_tblhotel_distnace_to_float));
        
        string IMigrationMetadata.Id
        {
            get { return "201609280600404_alter_tblhotel_distnace_to_float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
